username= input("Enter your username: ")
print("Welcome", username)
age= input("Enter your age: ")
print("age",age)
length= float(input("Please enter the length of the square: "))
option= input("Enter A to calculate area or P to calculate perimeter: ")
Area= ("Length*Length")
print("area")
